name: Turnip-adrenotools

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04-arm

    steps:
      - name: Update apt and install dependencies
        run: sudo apt update && sudo apt install -y python3 git

      - name: Clone, install, and build
        run: |
          git clone https://github.com/JustCallMeJade/Random-py-project
          cd Random-py-project
          pip install .
          build-now

      - name: Find zip in turnip_workdir
        id: find_zip
        run: |
          ZIP_PATH=$(find Random-py-project/turnip_workdir -maxdepth 1 -name "*.zip" | head -n 1)
          if [ -z "$ZIP_PATH" ]; then
            echo "No zip file found in turnip_workdir!"
            exit 1
          fi
          echo "zip_path=$ZIP_PATH" >> $GITHUB_OUTPUT
          echo "Found: $ZIP_PATH"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: turnip-build
          path: ${{ steps.find_zip.outputs.zip_path }}
          if-no-files-found: error
