name: Turnip Lavapipe

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-26.04-arm

    container:
      image: debian:sid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          chmod +x Build-lvp.sh
          ./Build-lvp.sh

      - name: Debug zip output
        run: |
          find lvp_workdir -type f -name "*.zip" -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lvp-build
          path: lvp_workdir/lvp/*.zip
          if-no-files-found: error

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.BUILD_VERSION }}
          name: v${{ env.BUILD_VERSION }}
          files: lvp_workdir/lvp/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
