name: Ubuntu 26.04 amd64 Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:26.04
      options: --platform=linux/amd64

    steps:
      - name: Show OS info
        run: |
          cat /etc/os-release

      - name: Show architecture
        run: |
          uname -m
